### ISSUE TITLE
Add German Umlauts

### ISSUE THREAD

**Issue by salcode** [salcode/fe-sanitize-title-js#1]
In [this fork](https://github.com/F10WB0T/fe-sanitize-title-js) by @F10WB0T, German Umlauts are added ( and some of my indentations are fixed 😀 ).

It makes sense to add those improvements here, as well.

Along with this we should add a test string that uses Umlauts in `fe_sanitize_title_js_shortcode()`.

**Comment by F10WB0T** [comment]
Haha, nasty indentations :) Did a pull request as well.

**Comment by salcode** [comment]
The following seems like a reasonable string to use when testing these characters,  
`Ä ä Ö ö Ü ü ß`.

When this string is processed with WordPress's PHP `sanitize_title()` function, the result is  
`a-a-o-o-u-u-s`

As a reminder, the goal of this project is to get the same behavior in JavaScript that we get from WordPress's PHP `sanitize_tilte()`.

~~Currently, our JavaScript code renders this string as  
`ae-ae-oe-oe-ue-ue-ss`~~

**Correction**: Our current JavaScript code does seem to render this test string the same as the WordPress PHP function `sanitize_title()`.

I determined this by adding the `[sanitize-title-js]` shortcode, where renders the test string with PHP and JavaScript.

Both rendered `a-a-o-o-u-u-s`

<img width="572" alt="screen shot 2018-05-09 at 22 51 58" src="https://user-images.githubusercontent.com/5194588/39849686-a2364668-53db-11e8-8090-a743a6e40a22.png">

@F10WB0T, if you run the PHP code `echo sanitize_title('Ä ä Ö ö Ü ü ß');` do you get the same `a-a-o-o-u-u-s`?

If not, I wonder if this could be affected by WordPress localization.

**Comment by F10WB0T** [comment]
@salcode, that's interesting. I think it's just as you assumed. The WordPress localization is affecting this function. When I run `echo sanitize_title('Ä ä Ö ö Ü ü ß');` I get `ae-ae-oe-oe-ue-ue-ss`. But when I switch the site language to English I get `a-a-o-o-u-u-s`.

**Comment by salcode** [comment]
Thanks for checking that out @F10WB0T, I'm not sure how best to handle this.

A couple of different thoughts cross my mind.

1.  Turn this whole thing into an AJAX call to WordPress and use the WordPress PHP `sanitize_title()` to do the work and return the value.
2.  Pass the localization language into the JavaScript function and add conditional language based logic there.
3.  Add an additional parameter to our JavaScript `wpFeSanitizeTitle()` function, to allow sending a custom mapping.  e.g.

```
wpFeSanitizeTitle(
    'My string to sanitize',
    {
         {'base':'AE','letters':'\u00c4'},
         {'base':'OE','letters':'\u00d6'}
    }
);
```

Right now, I'm leaning towards the 3rd option.  I realize this isn't a significant improvement to your use-case.  At this point, you're probably best off using your fork.

**Comment by salcode** [comment]
For now, this project is going emulate `sanitize_title()` when the *Site Language* is `English (United States)`. I've made a note of this in [the wiki](https://github.com/salcode/fe-sanitize-title-js/wiki/WordPress-Localization-Impact).

A big thanks to @F10WB0T for bringing this behavior to my attention.
