### ISSUE TITLE
&nbsp; is removed instead of being replaced with a dash

### ISSUE THREAD

**Issue by BenRutlandWeb** [salcode/fe-sanitize-title-js#14]
The WordPress PHP function replaces \&nbsp; with a dash whereas the JS function leaves it as it is.

Given the string (each 'space' is actually a \&nbsp;):
```html
This is some dummy text
```
The correct output should be:
```html
this-is-some-dummy-text
```
But the output is:
```html
this&nbsp;is&nbsp;some&nbsp;dummy&nbsp;text
```

Adding the unicode to the `defaultDiacriticsRemovalMap` should fix the issue.
```js
defaultDiacriticsRemovalMap = [
    {'base':'-', 'letters':'\u2013\u2014\u00A0'},
    ...
]
```

**Comment by salcode** [comment]
Hi @BenRutlandWeb,

Thanks for the bug report and the solution. This is now resolved in `v1.0.4`

This also lead to #15, so thank you for that as well.
